import Head from "next/head";
import { classes } from "typestyle";
import { Roboto } from "next/font/google";

import styles from "@/styles/about.styles";
import generalStyles from "@/styles/general.styles";
import Navigation from "@/components/molecules/Navigation";
import AboutMe from "@/components/molecules/About";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/portfolio/favicon.ico" />
      </Head>
      <Navigation />
      <main className={classes(generalStyles.main, roboto.className)}>
        <div className={classes(generalStyles.row, styles.headerSeperator)}>
          <div className={generalStyles.column(67)}>
            <AboutMe title="Zachary Aries" subTitle="Software Engineer" />
          </div>
          <div
            className={classes(
              styles.infoPanel,
              styles.profile,
              generalStyles.column(33)
            )}
          >
            <div>
              <h3>Profile</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc a
                purus facilisis, luctus ligula ac, viverra orci. Pellentesque
                habitant morbi tristique senectus et netus et malesuada fames ac
                turpis egestas. Integer at massa blandit, ullamcorper risus ac,
                mattis ligula. Pellentesque habitant morbi tristique senectus et
                netus et malesuada fames ac turpis egestas.
              </p>
            </div>
          </div>
        </div>
        <div className={generalStyles.row}>
          <div
            className={classes(
              generalStyles.column(67),
              generalStyles.verticalSpacing(40)
            )}
          >
            <h3>Work Experience</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc a
              purus facilisis, luctus ligula ac, viverra orci. Pellentesque
              habitant morbi tristique senectus et netus et malesuada fames ac
              turpis egestas. Integer at massa blandit, ullamcorper risus ac,
              mattis ligula. Pellentesque habitant morbi tristique senectus et
              netus et malesuada fames ac turpis egestas.
            </p>
          </div>
          <div
            className={classes(
              styles.infoPanel,
              generalStyles.column(33),
              generalStyles.verticalSpacing(40)
            )}
          >
            <div>
              <h3>Skills</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc a
                purus facilisis, luctus ligula ac, viverra orci. Pellentesque
                habitant morbi tristique senectus et netus et malesuada fames ac
                turpis egestas. Integer at massa blandit, ullamcorper risus ac,
                mattis ligula. Pellentesque habitant morbi tristique senectus et
                netus et malesuada fames ac turpis egestas.
              </p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
