import Head from "next/head";
import { Inter } from "next/font/google";

import styles from "@/styles/home.styles";
import Hero from "@/components/molecules/Hero";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  console.log(inter.className);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/portfolio/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <div className={styles.heroContainer}>
          <Hero title="Zach J. Aries" />
        </div>
      </main>
    </>
  );
}
